class BlogsController < ApplicationController
	def index
        
        #@content1 = "This is content generated by PostsController"
        
        @blogs = Blog.all 
        #instant variable 'articles' will hold all Posts taken from the database
        
    end
    
    def show
        #@blog = Blog.find(params[:id])
        @blog = Blog.friendly.find(params[:id])
        if request.path != blog_path(@blog)
            redirect_to @blog, status: :moved_permanently
        end
        #@type = @article.type_id
        @experiences = @blog.experiences

    end
    
    def edit
        #@blog = Blog.find(params[:id])
        @blog = Blog.friendly.find(params[:id])
    end
    
    def update
        #@blog = Blog.find(params[:id])
        @blog = Blog.friendly.find(params[:id])
        if @blog.update_attributes(article_params)
            redirect_to article_path, :notice => "Your blog article has been updated"
        else
            render "edit"
        end
    end
    
    def new
        @blog = Blog.new
        #@type = Type.all
    end
    
    def create
    end
      
    def destroy
    end
    
    def blog_params
        params.require(:blog).permit(:title, :body, :teaser, :banner_image, :thumbnail)
    end

end
